deploy-to-server:
  stage: deploy
  only:
    - main
  before_script:
    - echo 'start deployment'
    - whoami
  script:
    - cd /home/ubuntu/S07P12A605/
    - git pull origin main
    - cd backend
    - kill $(lsof -t -i:8080)
    - sudo mvn package
    - cd /home/ubuntu/S07P12A605/backend/target/
    - setsid nohup java -jar backend-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &
    - cd /home/ubuntu/S07P12A605/frontend/
    - sudo npm install
    - sudo npm run build
    - sudo service nginx restart
  after_script:
    - echo 'deployment is done'
  tags:
    - deploy
