deploy-to-server:
  stage: deploy
  only:
    - main
  before_script:
    - echo 'start deployment'
    - whoami
  script:
    - cd /home/ubuntu/S07P12A605/
    - git pull origin main
    - cd BE
    - kill $(lsof -t -i:8080)
    - sudo mvn package
    - cd /home/ubuntu/S07P12A605/BE/target/
    - setsid nohup java -jar crafts-1.0-SNAPSHOT.jar > /dev/null 2>&1 &
    - cd /home/ubuntu/S07P12A605/FE/
    - sudo npm install
    - sudo npm run build
    - sudo service nginx restart
  after_script:
    - echo 'deployment is done'
  tags:
    - deploy
